import { Section, Batch, Profile, Unit, MCQQuestion, VivaQuestion, ExamSession, SessionStudent } from '../types';
import { OFFICIAL_CSE_STUDENTS } from './officialStudents';

export const INITIAL_SECTIONS: Section[] = [
  { id: 'sec-a', section_code: 'A', section_name: 'Section A (CSE)', academic_year: '2025-2026', program: 'B.E. Computer Science', handling_faculty_name: 'Mr. Raghavendra G.S', handling_faculty_email: 'raghugs.cs@sode-edu.in', active: true },
  { id: 'sec-b', section_code: 'B', section_name: 'Section B (CSE)', academic_year: '2025-2026', program: 'B.E. Computer Science', handling_faculty_name: 'Ms. Ashritha K P', handling_faculty_email: 'ashritha.cs@sode-edu.in', active: true },
  { id: 'sec-c', section_code: 'C', section_name: 'Section C (CSE)', academic_year: '2025-2026', program: 'B.E. Computer Science', handling_faculty_name: 'Ms. R. Soundharya', handling_faculty_email: 'soundharya.cs@sode-edu.in', active: true },
];

export const INITIAL_BATCHES: Batch[] = [
  { id: 'batch-a1', section_id: 'sec-a', batch_code: 'A1', batch_name: 'Batch A1 (Roll 001 - 030)', academic_year: '2025-2026', program: 'B.E. Computer Science', active: true },
  { id: 'batch-a2', section_id: 'sec-a', batch_code: 'A2', batch_name: 'Batch A2 (Roll 031 - 060)', academic_year: '2025-2026', program: 'B.E. Computer Science', active: true },
  { id: 'batch-b1', section_id: 'sec-b', batch_code: 'B1', batch_name: 'Batch B1 (Roll 001 - 030)', academic_year: '2025-2026', program: 'B.E. Computer Science', active: true },
  { id: 'batch-b2', section_id: 'sec-b', batch_code: 'B2', batch_name: 'Batch B2 (Roll 031 - 060)', academic_year: '2025-2026', program: 'B.E. Computer Science', active: true },
  { id: 'batch-c1', section_id: 'sec-c', batch_code: 'C1', batch_name: 'Batch C1 (Roll 001 - 030)', academic_year: '2025-2026', program: 'B.E. Computer Science', active: true },
  { id: 'batch-c2', section_id: 'sec-c', batch_code: 'C2', batch_name: 'Batch C2 (Roll 031 - 060)', academic_year: '2025-2026', program: 'B.E. Computer Science', active: true },
];

export const INITIAL_PROFILES: Profile[] = [
  // Admin & Section Handling Faculty
  { id: 'user-admin', roll_number: 'ADMIN-01', full_name: 'System Administrator', email: 'admin@sode-edu.in', role: 'admin', active: true },
  { id: 'user-fac1', roll_number: 'FAC-CSE-01', full_name: 'Mr. Raghavendra G.S', email: 'raghugs.cs@sode-edu.in', section_id: 'sec-a', role: 'faculty', active: true },
  { id: 'user-fac2', roll_number: 'FAC-CSE-02', full_name: 'Ms. Ashritha K P', email: 'ashritha.cs@sode-edu.in', section_id: 'sec-b', role: 'faculty', active: true },
  { id: 'user-fac3', roll_number: 'FAC-CSE-03', full_name: 'Ms. R. Soundharya', email: 'soundharya.cs@sode-edu.in', section_id: 'sec-c', role: 'faculty', active: true },

  // Official Institutional Student Roster (145 Students from Updated 2026-2027 ODD Sem CSE Student List.xlsx)
  ...OFFICIAL_CSE_STUDENTS,
  // 1 Unassigned student awaiting final batch allocation to test batch assignment flow
  { id: 'stud-180', roll_number: '4MW25CS180', full_name: 'VIKRAM D SOUZA', email: 'vikram.25cs180@sode-edu.in', section_id: 'sec-c', batch_id: null, role: 'student', active: true },
];

export const INITIAL_UNITS: Unit[] = [
  {
    id: 'unit-1',
    unit_number: 1,
    title: 'Setting Up and Basic Commands',
    program_number: 'Exp 1',
    description: 'Initialize a new Git repository in a directory. Create a new file and add it to the staging area, and commit the changes with an appropriate commit message.',
    notes_url: 'https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository',
    key_takeaways: [
      'git init creates an empty repository or reinitializes an existing one by creating a .git directory',
      'git add stages file changes in the index ready for the next commit',
      'git commit creates a permanent snapshot of staged changes identified by a SHA-1 hash',
      'git status inspects files in the working directory and staging area',
    ],
    published: true,
    videos: [
      {
        id: 'vid-1',
        unit_id: 'unit-1',
        title: 'Git Setup, Staging Area, and Commit Life Cycle',
        source_type: 'youtube',
        source_url: 'https://www.youtube.com/watch?v=mAFoROnOfHs',
        duration_seconds: 600, // 10 minutes
      },
    ],
  },
  {
    id: 'unit-2',
    unit_number: 2,
    title: 'Creating and Managing Branches',
    program_number: 'Exp 2',
    description: 'Create a new branch named "feature-branch". Switch to the "master" branch. Merge the "feature-branch" into "master".',
    notes_url: 'https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging',
    key_takeaways: [
      'Branches represent independent lines of development and are lightweight movable pointers to commits',
      'git branch <name> creates a new branch pointer at HEAD',
      'git switch / git checkout moves HEAD to the designated branch',
      'Fast-forward merge simply advances the master pointer forward if no conflicting diverged commits exist',
    ],
    published: true,
    videos: [
      {
        id: 'vid-2',
        unit_id: 'unit-2',
        title: 'Branch Creation, Switching, and Fast-Forward Merges',
        source_type: 'youtube',
        source_url: 'https://www.youtube.com/watch?v=mAFoROnOfHs',
        duration_seconds: 540,
      },
    ],
  },
  {
    id: 'unit-3',
    unit_number: 3,
    title: 'Stashing and Workspace Switching',
    program_number: 'Exp 3',
    description: 'Write the commands to stash your changes, switch branches, and then apply the stashed changes.',
    notes_url: 'https://git-scm.com/book/en/v2/Git-Tools-Stashing-and-Cleaning',
    key_takeaways: [
      'git stash takes your uncommitted modifications (staged and unstaged) and saves them onto a dirty working directory stack',
      'git stash apply restores stashed changes while keeping the stash in the stack',
      'git stash pop restores stashed changes and immediately removes the item from the stack',
      'git stash -u allows stashing untracked files as well',
    ],
    published: true,
    videos: [
      {
        id: 'vid-3',
        unit_id: 'unit-3',
        title: 'Working with Git Stash, Apply, and Stack Management',
        source_type: 'youtube',
        source_url: 'https://www.youtube.com/watch?v=mAFoROnOfHs',
        duration_seconds: 480,
      },
    ],
  },
  {
    id: 'unit-4',
    unit_number: 4,
    title: 'Collaboration and Remote Repositories',
    program_number: 'Exp 4',
    description: 'Clone a remote Git repository to your local machine and inspect remotes.',
    notes_url: 'https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes',
    key_takeaways: [
      'git clone clones all repository data, commit objects, tags, and creates remote-tracking branches',
      'origin is the standard default alias Git gives to the remote repository cloned from',
      'git remote -v displays configured remote URLs and fetch/push targets',
      'Remote tracking branches cannot be edited directly; local branches must track them',
    ],
    published: true,
    videos: [
      {
        id: 'vid-4',
        unit_id: 'unit-4',
        title: 'Remote Repositories: Clone, Remotes, and Upstream Tracking',
        source_type: 'youtube',
        source_url: 'https://www.youtube.com/watch?v=mAFoROnOfHs',
        duration_seconds: 620,
      },
    ],
  },
  {
    id: 'unit-5',
    unit_number: 5,
    title: 'Fetch and Rebase Operations',
    program_number: 'Exp 5',
    description: 'Fetch the latest changes from a remote repository and rebase your local branch onto the updated remote branch.',
    notes_url: 'https://git-scm.com/book/en/v2/Git-Branching-Rebasing',
    key_takeaways: [
      'git fetch retrieves remote commits without touching your working tree or moving local branch pointers',
      'git rebase <upstream> replays your local branch commits on top of the fetched upstream commit',
      'Rebasing results in a clean, linear history without redundant merge commits',
      'Golden Rule: Never rebase commits that exist outside your local repository on shared public branches',
    ],
    published: true,
    videos: [
      {
        id: 'vid-5',
        unit_id: 'unit-5',
        title: 'Git Fetch vs Pull and Clean Linear History with Git Rebase',
        source_type: 'youtube',
        source_url: 'https://www.youtube.com/watch?v=mAFoROnOfHs',
        duration_seconds: 680,
      },
    ],
  },
  {
    id: 'unit-6',
    unit_number: 6,
    title: 'Custom Commit Message Merges',
    program_number: 'Exp 6',
    description: 'Write the command to merge "feature-branch" into "master" while providing a custom commit message for the merge.',
    notes_url: 'https://git-scm.com/docs/git-merge',
    key_takeaways: [
      'git merge --no-ff forces Git to create a merge commit even if a fast-forward was possible',
      'The -m "message" flag attaches a custom message to the merge commit',
      'Merge conflicts happen when different branches modify the same line or lines in a file',
      'Standard conflict markers: <<<<<<< HEAD, =======, and >>>>>>> branch_name',
    ],
    published: true,
    videos: [
      {
        id: 'vid-6',
        unit_id: 'unit-6',
        title: 'Custom Merge Commits, No-FF Policy, and Conflict Resolution',
        source_type: 'youtube',
        source_url: 'https://www.youtube.com/watch?v=mAFoROnOfHs',
        duration_seconds: 590,
      },
    ],
  },
  {
    id: 'unit-7',
    unit_number: 7,
    title: 'Git Tags and Releases',
    program_number: 'Exp 7',
    description: 'Write the command to create a lightweight Git tag named "v1.0" for a commit in your local repository.',
    key_takeaways: [
      'Lightweight tags are simple bookmarks pointing to a specific commit',
      'Annotated tags contain full author information, date, release message and optional GPG signature',
      'git tag v1.0 creates a lightweight tag; git tag -a v1.0 -m "Release" creates an annotated tag',
      'Tags do not automatically transfer to remotes without git push origin --tags',
    ],
    published: false, // Coming soon initially per prompt
  },
  {
    id: 'unit-8',
    unit_number: 8,
    title: 'Advanced Git: Cherry-Picking',
    program_number: 'Exp 8',
    description: 'Write the command to cherry-pick a range of commits from "source-branch" to the current branch.',
    key_takeaways: [
      'git cherry-pick applies the diff introduced by an existing commit to your current branch',
      'Cherry-pick generates a new commit with a new SHA hash',
      'Range syntax: git cherry-pick A..B (excluding A) or A^..B (including A)',
      'Ideal for applying specific bug fixes or features without bringing unrelated commits',
    ],
    published: false,
  },
  {
    id: 'unit-9',
    unit_number: 9,
    title: 'Analyzing History: Inspecting Commits',
    program_number: 'Exp 9',
    description: 'Given a commit ID, how would you use Git to view the details of that specific commit including author, date, and commit message?',
    key_takeaways: [
      'git show <commit-id> displays metadata, author, date, message and the full diff',
      'git show <commit-id>:<path> inspects a specific file version as it existed in that commit',
      'Git objects (blobs, trees, commits, tags) are stored by cryptographic hashes',
    ],
    published: false,
  },
  {
    id: 'unit-10',
    unit_number: 10,
    title: 'Filtered History Analysis',
    program_number: 'Exp 10',
    description: 'Write the Git command to display all commits made by author "JohnDoe" between January 1, 2025 and December 31, 2025.',
    key_takeaways: [
      'git log --author="JohnDoe" filters commits matching the author pattern',
      '--since="2025-01-01" --until="2025-12-31" restricts commits to a specific date interval',
      '--grep="feature" filters commit messages by keywords',
      'Filters can be combined to perform precise repository forensic audits',
    ],
    published: false,
  },
  {
    id: 'unit-11',
    unit_number: 11,
    title: 'Commit Log Limits and Formatting',
    program_number: 'Exp 11',
    description: 'Write the command to display the last five commits in the repository history formatted concisely.',
    key_takeaways: [
      'git log -n 5 or git log -5 limits the output to the last 5 commits',
      'git log --oneline outputs 7-character abbreviated hash and the commit subject line',
      'git log --graph displays visual ASCII branch and merge topology',
      'git log --stat shows changed files with insertions and deletions summary',
    ],
    published: false,
  },
  {
    id: 'unit-12',
    unit_number: 12,
    title: 'Undoing Changes in History',
    program_number: 'Exp 12',
    description: 'Write the command to undo the changes introduced by the commit with the ID "abc123".',
    key_takeaways: [
      'git revert <hash> creates a new commit that records the exact inverse diff of the target commit',
      'git revert is non-destructive and safe for shared remote branches',
      'git reset moves the branch pointer backward; --soft preserves staged changes, --mixed un-stages them, --hard wipes working directory',
      'git checkout / git restore can discard uncommitted file modifications',
    ],
    published: false,
  },
];

export const INITIAL_MCQS: MCQQuestion[] = [
  // Unit 1
  {
    id: 'mcq-1',
    unit_id: 'unit-1',
    topic: 'Git Setup & Initialization',
    difficulty: 'Easy',
    question_text: 'Which Git command initializes a brand-new Git repository inside the current working directory?',
    code_snippet: '$ mkdir my-project\n$ cd my-project\n$ ???',
    explanation: '`git init` creates the hidden `.git` directory containing object storage, references, configuration, and index.',
    tags: ['git init', 'basics'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-1-a', option_key: 'A', option_text: 'git start', is_correct: false },
      { id: 'opt-1-b', option_key: 'B', option_text: 'git init', is_correct: true },
      { id: 'opt-1-c', option_key: 'C', option_text: 'git create-repo', is_correct: false },
      { id: 'opt-1-d', option_key: 'D', option_text: 'git setup', is_correct: false },
    ],
  },
  {
    id: 'mcq-2',
    unit_id: 'unit-1',
    topic: 'Staging Area',
    difficulty: 'Easy',
    question_text: 'What is the primary function of the Git staging area (index)?',
    explanation: 'The staging area allows developers to preview, craft, and curate exact snapshots before committing them permanently to repository history.',
    tags: ['staging', 'index'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-2-a', option_key: 'A', option_text: 'It permanently deploys code to the remote GitLab server', is_correct: false },
      { id: 'opt-2-b', option_key: 'B', option_text: 'It acts as an intermediate cache where changes are prepared before creating a commit', is_correct: true },
      { id: 'opt-2-c', option_key: 'C', option_text: 'It resolves all merge conflicts automatically', is_correct: false },
      { id: 'opt-2-d', option_key: 'D', option_text: 'It stores encrypted credentials for SSH keys', is_correct: false },
    ],
  },
  {
    id: 'mcq-3',
    unit_id: 'unit-1',
    topic: 'Commit Syntax',
    difficulty: 'Medium',
    question_text: 'What command stages all modified and tracked files, and records a commit with a message in one step?',
    explanation: '`git commit -am "msg"` stages modified tracked files (-a) and attaches the commit message (-m). It does not add newly created untracked files.',
    tags: ['commit', 'flags'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-3-a', option_key: 'A', option_text: 'git commit -am "message"', is_correct: true },
      { id: 'opt-3-b', option_key: 'B', option_text: 'git push -m "message"', is_correct: false },
      { id: 'opt-3-c', option_key: 'C', option_text: 'git stage --all "message"', is_correct: false },
      { id: 'opt-3-d', option_key: 'D', option_text: 'git save -a -m "message"', is_correct: false },
    ],
  },

  // Unit 2
  {
    id: 'mcq-4',
    unit_id: 'unit-2',
    topic: 'Branch Creation',
    difficulty: 'Easy',
    question_text: 'Which command creates a new branch named `feature-login` and immediately switches to it?',
    explanation: '`git checkout -b <name>` or `git switch -c <name>` creates and switches to the new branch.',
    tags: ['branch', 'checkout'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-4-a', option_key: 'A', option_text: 'git branch --move feature-login', is_correct: false },
      { id: 'opt-4-b', option_key: 'B', option_text: 'git checkout -b feature-login', is_correct: true },
      { id: 'opt-4-c', option_key: 'C', option_text: 'git switch --force feature-login', is_correct: false },
      { id: 'opt-4-d', option_key: 'D', option_text: 'git merge -b feature-login', is_correct: false },
    ],
  },
  {
    id: 'mcq-5',
    unit_id: 'unit-2',
    topic: 'Fast-Forward Merge',
    difficulty: 'Medium',
    question_text: 'Under what condition will Git perform a fast-forward merge when merging `feature` into `master`?',
    explanation: 'If `master` has not received any new commits since `feature` was branched, the `master` pointer simply advances forward to point to the tip of `feature`.',
    tags: ['merge', 'fast-forward'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-5-a', option_key: 'A', option_text: 'When both branches have diverged commits on the same file', is_correct: false },
      { id: 'opt-5-b', option_key: 'B', option_text: 'When there are no new commits on master since feature branched off', is_correct: true },
      { id: 'opt-5-c', option_key: 'C', option_text: 'Only when the --no-ff flag is explicitly passed', is_correct: false },
      { id: 'opt-5-d', option_key: 'D', option_text: 'When the repository is cloned over SSH instead of HTTPS', is_correct: false },
    ],
  },

  // Unit 3
  {
    id: 'mcq-6',
    unit_id: 'unit-3',
    topic: 'Git Stashing',
    difficulty: 'Medium',
    question_text: 'What happens to the stash list after you successfully execute `git stash pop`?',
    explanation: '`git stash pop` applies the top stash (`stash@{0}`) and drops it from the stash stack. In contrast, `git stash apply` keeps it in the stack.',
    tags: ['stash', 'pop'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-6-a', option_key: 'A', option_text: 'The stash is applied and permanently retained on the stash list', is_correct: false },
      { id: 'opt-6-b', option_key: 'B', option_text: 'The top stash is applied to the working directory and removed from the stash list', is_correct: true },
      { id: 'opt-6-c', option_key: 'C', option_text: 'All stashes in the entire repository are deleted', is_correct: false },
      { id: 'opt-6-d', option_key: 'D', option_text: 'A new commit is automatically committed to origin', is_correct: false },
    ],
  },
  {
    id: 'mcq-7',
    unit_id: 'unit-3',
    topic: 'Stashing Untracked Files',
    difficulty: 'Hard',
    question_text: 'By default, `git stash` ignores newly created, untracked files. Which flag forces Git to stash untracked files as well?',
    explanation: '`git stash -u` (or `--include-untracked`) instructs Git to include untracked files in the stash snapshot.',
    tags: ['stash', 'untracked'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-7-a', option_key: 'A', option_text: 'git stash -f', is_correct: false },
      { id: 'opt-7-b', option_key: 'B', option_text: 'git stash -u', is_correct: true },
      { id: 'opt-7-c', option_key: 'C', option_text: 'git stash --force-all', is_correct: false },
      { id: 'opt-7-d', option_key: 'D', option_text: 'git stash -r', is_correct: false },
    ],
  },

  // Unit 4
  {
    id: 'mcq-8',
    unit_id: 'unit-4',
    topic: 'Remote Repositories',
    difficulty: 'Easy',
    question_text: 'Which command lists all configured remote repository names along with their fetch and push URL addresses?',
    explanation: '`git remote -v` lists all configured remotes with their verbose URLs.',
    tags: ['remotes', 'urls'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-8-a', option_key: 'A', option_text: 'git remote -v', is_correct: true },
      { id: 'opt-8-b', option_key: 'B', option_text: 'git remotes --list-all', is_correct: false },
      { id: 'opt-8-c', option_key: 'C', option_text: 'git fetch --show', is_correct: false },
      { id: 'opt-8-d', option_key: 'D', option_text: 'git config remotes', is_correct: false },
    ],
  },
  {
    id: 'mcq-9',
    unit_id: 'unit-4',
    topic: 'Remote Tracking Branches',
    difficulty: 'Medium',
    question_text: 'In Git, what does `origin/master` represent?',
    explanation: '`origin/master` is a remote-tracking branch representing the state of the `master` branch on the remote named `origin` as of the last fetch/clone.',
    tags: ['remotes', 'tracking'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-9-a', option_key: 'A', option_text: 'A local copy that can be committed to directly by running git commit', is_correct: false },
      { id: 'opt-9-b', option_key: 'B', option_text: 'A remote-tracking branch reflecting the state of master on the origin remote at last network communication', is_correct: true },
      { id: 'opt-9-c', option_key: 'C', option_text: 'A virtual branch that only exists inside GitLab CI runner containers', is_correct: false },
      { id: 'opt-9-d', option_key: 'D', option_text: 'A backup branch created when merge conflicts occur', is_correct: false },
    ],
  },

  // Unit 5
  {
    id: 'mcq-10',
    unit_id: 'unit-5',
    topic: 'Fetch vs Pull',
    difficulty: 'Medium',
    question_text: 'What is the key technical difference between `git fetch` and `git pull`?',
    explanation: '`git fetch` only downloads data without touching the working branch; `git pull` runs `git fetch` followed immediately by `git merge`.',
    tags: ['fetch', 'pull'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-10-a', option_key: 'A', option_text: 'git fetch updates local working files; git pull only inspects remote commits', is_correct: false },
      { id: 'opt-10-b', option_key: 'B', option_text: 'git fetch downloads commits without modifying local working branches; git pull fetches and automatically merges', is_correct: true },
      { id: 'opt-10-c', option_key: 'C', option_text: 'git fetch requires admin permissions; git pull does not', is_correct: false },
      { id: 'opt-10-d', option_key: 'D', option_text: 'There is no difference; they are exact aliases', is_correct: false },
    ],
  },
  {
    id: 'mcq-11',
    unit_id: 'unit-5',
    topic: 'Git Rebase',
    difficulty: 'Hard',
    question_text: 'Consider the diagram below. What does `git rebase origin/master` do to local commits C1 and C2 on branch `feature`?',
    code_snippet: 'master:  A --- B --- C (origin/master)\nfeature:        \\\n                 D --- E (HEAD)',
    explanation: 'Rebase un-commits D and E, moves HEAD to C, and replays D and E on top of C, generating brand-new commit hashes D\' and E\'.',
    tags: ['rebase', 'history'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-11-a', option_key: 'A', option_text: 'Creates a diamond-shaped merge commit on top of E', is_correct: false },
      { id: 'opt-11-b', option_key: 'B', option_text: 'Temporarily stashes D and E, advances base to C, and replays D and E on top of C with new commit hashes', is_correct: true },
      { id: 'opt-11-c', option_key: 'C', option_text: 'Deletes branch master and replaces it with feature', is_correct: false },
      { id: 'opt-11-d', option_key: 'D', option_text: 'Discards commits D and E completely', is_correct: false },
    ],
  },

  // Unit 6
  {
    id: 'mcq-12',
    unit_id: 'unit-6',
    topic: 'Non-Fast-Forward Merge',
    difficulty: 'Medium',
    question_text: 'Which flag forces Git to create an explicit merge commit with its own commit message, even if a fast-forward merge is possible?',
    explanation: '`git merge --no-ff` ensures a dedicated merge commit is created, preserving historical record of a feature branch.',
    tags: ['merge', 'no-ff'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-12-a', option_key: 'A', option_text: 'git merge --no-ff', is_correct: true },
      { id: 'opt-12-b', option_key: 'B', option_text: 'git merge --force-commit', is_correct: false },
      { id: 'opt-12-c', option_key: 'C', option_text: 'git merge --strict', is_correct: false },
      { id: 'opt-12-d', option_key: 'D', option_text: 'git merge --two-way', is_correct: false },
    ],
  },
  {
    id: 'mcq-13',
    unit_id: 'unit-6',
    topic: 'Merge Conflict Markers',
    difficulty: 'Easy',
    question_text: 'When a merge conflict occurs in Git, which marker denotes the beginning of the conflicting changes on the CURRENT checked-out branch?',
    code_snippet: '<<<<<<< HEAD\nconst port = 3000;\n=======\nconst port = 8080;\n>>>>>>> feature-branch',
    explanation: '`<<<<<<< HEAD` indicates the start of the version from the currently active branch (HEAD).',
    tags: ['conflict', 'markers'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-13-a', option_key: 'A', option_text: '=======' , is_correct: false },
      { id: 'opt-13-b', option_key: 'B', option_text: '<<<<<<< HEAD', is_correct: true },
      { id: 'opt-13-c', option_key: 'C', option_text: '>>>>>>> feature-branch', is_correct: false },
      { id: 'opt-13-d', option_key: 'D', option_text: '||||||| merged common ancestors', is_correct: false },
    ],
  },

  // Unit 7
  {
    id: 'mcq-14',
    unit_id: 'unit-7',
    topic: 'Git Tags',
    difficulty: 'Easy',
    question_text: 'Which command creates an annotated Git tag named `v1.0` with the message "First production release"?',
    explanation: '`git tag -a v1.0 -m "First production release"` creates an annotated tag containing metadata and message.',
    tags: ['tag', 'annotated'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-14-a', option_key: 'A', option_text: 'git tag -a v1.0 -m "First production release"', is_correct: true },
      { id: 'opt-14-b', option_key: 'B', option_text: 'git create-tag v1.0 --message "First production release"', is_correct: false },
      { id: 'opt-14-c', option_key: 'C', option_text: 'git release v1.0 -m "First production release"', is_correct: false },
      { id: 'opt-14-d', option_key: 'D', option_text: 'git checkpoint v1.0', is_correct: false },
    ],
  },
  {
    id: 'mcq-15',
    unit_id: 'unit-7',
    topic: 'Pushing Tags',
    difficulty: 'Medium',
    question_text: 'By default, running `git push origin master` does NOT push local tags to the remote repository. How can you push all tags?',
    explanation: 'Tags must be pushed explicitly using `git push origin --tags` or `git push origin <tagname>`.',
    tags: ['tags', 'push'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-15-a', option_key: 'A', option_text: 'git push origin --all-objects', is_correct: false },
      { id: 'opt-15-b', option_key: 'B', option_text: 'git push origin --tags', is_correct: true },
      { id: 'opt-15-c', option_key: 'C', option_text: 'git sync-tags origin', is_correct: false },
      { id: 'opt-15-d', option_key: 'D', option_text: 'git tag --push', is_correct: false },
    ],
  },

  // Unit 8
  {
    id: 'mcq-16',
    unit_id: 'unit-8',
    topic: 'Cherry-Pick Range',
    difficulty: 'Hard',
    question_text: 'Which command applies the commits from `commitA` (exclusive) up to and including `commitB` (inclusive) onto the current branch?',
    explanation: 'The range notation `commitA..commitB` in `git cherry-pick` applies commits starting after commitA up to commitB.',
    tags: ['cherry-pick', 'range'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-16-a', option_key: 'A', option_text: 'git cherry-pick commitA..commitB', is_correct: true },
      { id: 'opt-16-b', option_key: 'B', option_text: 'git cherry-pick --between commitA commitB', is_correct: false },
      { id: 'opt-16-c', option_key: 'C', option_text: 'git merge-range commitA commitB', is_correct: false },
      { id: 'opt-16-d', option_key: 'D', option_text: 'git patch commitA commitB', is_correct: false },
    ],
  },

  // Unit 9
  {
    id: 'mcq-17',
    unit_id: 'unit-9',
    topic: 'Inspecting Commits',
    difficulty: 'Easy',
    question_text: 'Which command outputs the complete details of a commit `7f3d2a`, including author, timestamp, commit log, and diff patch?',
    explanation: '`git show 7f3d2a` shows the commit metadata along with the unified diff of changes made by that commit.',
    tags: ['git show', 'inspection'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-17-a', option_key: 'A', option_text: 'git status 7f3d2a', is_correct: false },
      { id: 'opt-17-b', option_key: 'B', option_text: 'git show 7f3d2a', is_correct: true },
      { id: 'opt-17-c', option_key: 'C', option_text: 'git inspect 7f3d2a', is_correct: false },
      { id: 'opt-17-d', option_key: 'D', option_text: 'git view 7f3d2a', is_correct: false },
    ],
  },

  // Unit 10
  {
    id: 'mcq-18',
    unit_id: 'unit-10',
    topic: 'Git Log Filtering',
    difficulty: 'Medium',
    question_text: 'Which command correctly displays all commits authored by "JohnDoe" in the year 2025?',
    explanation: '`git log --author="JohnDoe" --since="2025-01-01" --until="2025-12-31"` filters commits by author and bounds date ranges.',
    tags: ['git log', 'filters'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-18-a', option_key: 'A', option_text: 'git log --author="JohnDoe" --since="2025-01-01" --until="2025-12-31"', is_correct: true },
      { id: 'opt-18-b', option_key: 'B', option_text: 'git search --user "JohnDoe" --year 2025', is_correct: false },
      { id: 'opt-18-c', option_key: 'C', option_text: 'git filter-log author:JohnDoe date:2025', is_correct: false },
      { id: 'opt-18-d', option_key: 'D', option_text: 'git log -u JohnDoe -d "2025-01-01 to 2025-12-31"', is_correct: false },
    ],
  },

  // Unit 11
  {
    id: 'mcq-19',
    unit_id: 'unit-11',
    topic: 'Log Limiting',
    difficulty: 'Easy',
    question_text: 'Which command displays only the last 5 commits in the repository history on a single condensed line each?',
    explanation: '`git log -n 5 --oneline` restricts output to 5 entries and formats each as an abbreviated hash plus subject line.',
    tags: ['git log', 'oneline', 'limits'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-19-a', option_key: 'A', option_text: 'git log -n 5 --oneline', is_correct: true },
      { id: 'opt-19-b', option_key: 'B', option_text: 'git history --limit 5 --short', is_correct: false },
      { id: 'opt-19-c', option_key: 'C', option_text: 'git commits -5 --single-line', is_correct: false },
      { id: 'opt-19-d', option_key: 'D', option_text: 'git show -n 5 --compact', is_correct: false },
    ],
  },

  // Unit 12
  {
    id: 'mcq-20',
    unit_id: 'unit-12',
    topic: 'Undoing Commits',
    difficulty: 'Medium',
    question_text: 'What command safely undoes the changes introduced by commit `abc123` by creating a new forward-facing inverse commit?',
    explanation: '`git revert abc123` creates a new commit that undoes the changes made by commit abc123, making it safe for public branches.',
    tags: ['git revert', 'undo'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-20-a', option_key: 'A', option_text: 'git delete commit abc123', is_correct: false },
      { id: 'opt-20-b', option_key: 'B', option_text: 'git revert abc123', is_correct: true },
      { id: 'opt-20-c', option_key: 'C', option_text: 'git reset --hard HEAD~10', is_correct: false },
      { id: 'opt-20-d', option_key: 'D', option_text: 'git erase abc123', is_correct: false },
    ],
  },
  {
    id: 'mcq-21',
    unit_id: 'unit-12',
    topic: 'Git Reset Modes',
    difficulty: 'Hard',
    question_text: 'What is the effect of running `git reset --soft HEAD~1`?',
    explanation: '`git reset --soft` moves the HEAD pointer back by one commit while leaving all the modified files in the staging area (index) intact.',
    tags: ['git reset', 'soft'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-21-a', option_key: 'A', option_text: 'Discards all changes permanently from the hard disk', is_correct: false },
      { id: 'opt-21-b', option_key: 'B', option_text: 'Moves HEAD back one commit, but keeps all changes staged in the index', is_correct: true },
      { id: 'opt-21-c', option_key: 'C', option_text: 'Deletes the current branch entirely', is_correct: false },
      { id: 'opt-21-d', option_key: 'D', option_text: 'Un-stages files but keeps them in working directory', is_correct: false },
    ],
  },
  {
    id: 'mcq-22',
    unit_id: 'unit-1',
    topic: 'Git Configuration',
    difficulty: 'Easy',
    question_text: 'Which command sets your global commit author name across all Git repositories on your computer?',
    explanation: '`git config --global user.name "Name"` sets the author name globally in ~/.gitconfig.',
    tags: ['git config', 'author'],
    is_practice: false,
    active: true,
    options: [
      { id: 'opt-22-a', option_key: 'A', option_text: 'git config --global user.name "Your Name"', is_correct: true },
      { id: 'opt-22-b', option_key: 'B', option_text: 'git set-author "Your Name"', is_correct: false },
      { id: 'opt-22-c', option_key: 'C', option_text: 'git user --name "Your Name"', is_correct: false },
      { id: 'opt-22-d', option_key: 'D', option_text: 'git profile --update "Your Name"', is_correct: false },
    ],
  },
];

export const INITIAL_VIVA_QUESTIONS: VivaQuestion[] = [
  {
    id: 'viva-1',
    unit_id: 'unit-1',
    topic: 'Git Architecture & Lifecycle',
    difficulty: 'Medium',
    question_text: 'Explain the three main states/areas in Git (Working Directory, Staging Area, and Repository). How do files move between them?',
    reference_answer: 'Git manages files across three primary areas: 1) Working Directory: local files being edited. Running git add moves modified files to 2) Staging Area (Index): prepares a snapshot for commit. Running git commit moves staged files into 3) Repository (.git directory): immutable objects stored permanently as commit snapshots with SHA-1 hashes.',
    key_concepts: [
      'Working Directory / Working Tree',
      'Staging Area / Index',
      'Git Repository / Commit Object',
      'git add command',
      'git commit command',
    ],
    rubric: 'Full marks (10) for accurately describing all three states and the transition commands. Deduct 2 marks for omitting staging explanation.',
    max_marks: 10,
    active: true,
  },
  {
    id: 'viva-2',
    unit_id: 'unit-2',
    topic: 'Git Branching Mechanics',
    difficulty: 'Medium',
    question_text: 'What is a branch in Git under the hood? Explain how Git branches differ from branches in traditional VCS like SVN.',
    reference_answer: 'Under the hood, a Git branch is simply a lightweight, 41-byte text file containing a 40-character SHA-1 hash pointing to a specific commit. Unlike Subversion (SVN) where creating a branch copies the entire directory tree onto the server, creating a branch in Git is instantaneous and takes zero extra storage until new commits are recorded.',
    key_concepts: [
      'Pointer to a commit / SHA-1 hash',
      'Lightweight text reference in .git/refs/heads/',
      'Zero storage overhead compared to full copy systems (SVN)',
      'HEAD pointer referencing current branch',
    ],
    rubric: '10 marks for explaining the pointer concept and contrast with directory copies in SVN.',
    max_marks: 10,
    active: true,
  },
  {
    id: 'viva-3',
    unit_id: 'unit-3',
    topic: 'Git Stashing',
    difficulty: 'Medium',
    question_text: 'Describe a practical scenario where git stash is indispensable. What is the difference between git stash apply and git stash pop?',
    reference_answer: 'Scenario: When working on an incomplete feature branch and an urgent production bug requires switching branches immediately without committing half-finished code. git stash temporarily saves modified files onto a stack. git stash apply reapplies the changes while keeping them on the stash stack; git stash pop reapplies the changes and removes them from the stack.',
    key_concepts: [
      'Urgent context switch without dirty commits',
      'Stash stack / LIFO stack',
      'git stash apply retains stash entry',
      'git stash pop removes stash entry',
    ],
    rubric: '10 marks for realistic practical scenario and clear contrast between apply and pop.',
    max_marks: 10,
    active: true,
  },
  {
    id: 'viva-4',
    unit_id: 'unit-5',
    topic: 'Rebase vs Merge',
    difficulty: 'Hard',
    question_text: 'Compare git merge versus git rebase. What are the advantages of each, and what is the "Golden Rule of Rebasing"?',
    reference_answer: 'git merge creates a non-destructive merge commit tying two histories together, preserving exact chronological history and context. git rebase replays local commits on top of another base, producing a clean linear history. The Golden Rule of Rebasing is: Never rebase commits that have been pushed to a public/shared repository that other developers rely on, because it changes commit hashes and rewrites shared history.',
    key_concepts: [
      'Merge preserves true non-linear history with merge commit',
      'Rebase creates clean linear history by replaying commits',
      'Rebase generates new commit SHA-1 hashes',
      'Golden Rule: Never rebase shared/public branches',
    ],
    rubric: '10 marks for comprehensive comparison and explicit mention of the Golden Rule of Rebasing.',
    max_marks: 10,
    active: true,
  },
  {
    id: 'viva-5',
    unit_id: 'unit-12',
    topic: 'Undoing Changes Safely',
    difficulty: 'Hard',
    question_text: 'Explain the difference between git revert and git reset --hard. In what circumstances must you use git revert instead of git reset?',
    reference_answer: 'git revert is a forward operation that creates a brand new commit introducing inverse modifications, preserving past commit history. git reset --hard rewrites history by moving the branch pointer backward and destroying uncommitted and committed modifications in the working tree. git revert MUST be used when commits have already been pushed to a shared remote repository so other team members histories are not broken.',
    key_concepts: [
      'git revert creates a forward inverse commit',
      'git reset --hard discards commits and moves branch pointer backward',
      'Public/shared branch safety requires git revert',
      'Destructive vs Non-destructive history operations',
    ],
    rubric: '10 marks for explaining forward inverse commit vs pointer rewind and public branch safety requirement.',
    max_marks: 10,
    active: true,
  },
];

export const INITIAL_EXAM_SESSIONS: ExamSession[] = [
  {
    id: 'sess-01',
    name: 'Lab Exam CIE - 25CSAE370 (Batch A1 & A2)',
    date: '2026-10-04',
    status: 'lab_in_progress', // Active lab session
    video_gate_mode: 'strict',
    part_order: 'quiz_then_viva',
    quiz_duration_seconds: 1200, // 20 minutes
    number_of_mcqs: 12,
    number_of_viva_questions: 5,
    proctoring_settings: {
      webcam: false,
      fullscreen: true,
      anti_cheat: true,
    },
    violation_threshold: 3,
    auto_open_when_lab_done: true,
    close_grace_seconds: 120,
    created_by: 'user-fac1',
    target_batch_ids: ['batch-a1', 'batch-a2'],
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SESSION_STUDENTS: SessionStudent[] = [
  // Student 1: Lab completed, Quiz opened
  {
    id: 'ss-01',
    session_id: 'sess-01',
    student_id: 'stud-01',
    section_id_snapshot: 'sec-a',
    batch_id_snapshot: 'batch-a1',
    lab_status: 'completed',
    lab_completed_at: '2026-10-04T09:15:00Z',
    lab_completed_by: 'user-fac1',
    lab_marks: 28,
    lab_remarks: 'Executed Exp 1 & Exp 2 commands correctly with clean branch merge.',
    quiz_open: true,
    viva_open: false,
    opened_by: 'user-fac1',
    opened_at: '2026-10-04T09:20:00Z',
    extra_time_seconds: 0,
    gate_override_reason: null,
    retake_allowed: false,
    marks_state: 'draft',
  },
  // Student 2: Lab pending
  {
    id: 'ss-02',
    session_id: 'sess-01',
    student_id: 'stud-02',
    section_id_snapshot: 'sec-a',
    batch_id_snapshot: 'batch-a1',
    lab_status: 'pending',
    lab_completed_at: null,
    lab_completed_by: null,
    lab_marks: null,
    lab_remarks: null,
    quiz_open: false,
    viva_open: false,
    opened_by: null,
    opened_at: null,
    extra_time_seconds: 0,
    gate_override_reason: null,
    retake_allowed: false,
    marks_state: 'draft',
  },
  // Student 3: Lab completed, both opened
  {
    id: 'ss-03',
    session_id: 'sess-01',
    student_id: 'stud-03',
    section_id_snapshot: 'sec-a',
    batch_id_snapshot: 'batch-a1',
    lab_status: 'completed',
    lab_completed_at: '2026-10-04T09:18:00Z',
    lab_completed_by: 'user-fac1',
    lab_marks: 29,
    lab_remarks: 'Excellent execution of cherry-pick and custom commit messages.',
    quiz_open: true,
    viva_open: true,
    opened_by: 'user-fac1',
    opened_at: '2026-10-04T09:20:00Z',
    extra_time_seconds: 0,
    gate_override_reason: null,
    retake_allowed: false,
    marks_state: 'draft',
  },
  // Student 4: Lab completed, submitted
  {
    id: 'ss-04',
    session_id: 'sess-01',
    student_id: 'stud-04',
    section_id_snapshot: 'sec-a',
    batch_id_snapshot: 'batch-a1',
    lab_status: 'completed',
    lab_completed_at: '2026-10-04T09:10:00Z',
    lab_completed_by: 'user-fac1',
    lab_marks: 30,
    lab_remarks: 'Perfect git rebase and stash demonstration.',
    quiz_open: true,
    viva_open: true,
    opened_by: 'user-fac1',
    opened_at: '2026-10-04T09:15:00Z',
    extra_time_seconds: 0,
    gate_override_reason: null,
    retake_allowed: false,
    marks_state: 'draft',
  },
  // Student 6: In Batch A2, Lab pending
  {
    id: 'ss-06',
    session_id: 'sess-01',
    student_id: 'stud-06',
    section_id_snapshot: 'sec-a',
    batch_id_snapshot: 'batch-a2',
    lab_status: 'pending',
    lab_completed_at: null,
    lab_completed_by: null,
    lab_marks: null,
    lab_remarks: null,
    quiz_open: false,
    viva_open: false,
    opened_by: null,
    opened_at: null,
    extra_time_seconds: 0,
    gate_override_reason: null,
    retake_allowed: false,
    marks_state: 'draft',
  },
  // Student 7: In Batch A2, Lab completed
  {
    id: 'ss-07',
    session_id: 'sess-01',
    student_id: 'stud-07',
    section_id_snapshot: 'sec-a',
    batch_id_snapshot: 'batch-a2',
    lab_status: 'completed',
    lab_completed_at: '2026-10-04T09:25:00Z',
    lab_completed_by: 'user-fac2',
    lab_marks: 27,
    lab_remarks: 'Good understanding of tags and releases.',
    quiz_open: true,
    viva_open: true,
    opened_by: 'user-fac2',
    opened_at: '2026-10-04T09:25:00Z',
    extra_time_seconds: 300,
    gate_override_reason: null,
    retake_allowed: false,
    marks_state: 'draft',
  },
];
